### ISSUE TITLE
invalid test case

### ISSUE THREAD

**Issue by danmarsden** [paywallz/Foxtrot#21]
tests/advanced_testcase.php should just be deleted at this stage as it is not valid.

**Comment by BarmaleyHD** [comment]
Thanks. Done.

**Comment by danmarsden** [comment]
Just a warning - looks like you have made some changes to your dev branch and others to your master branch... you really should be doing development in a single branch and then using the merge process to bring all your changes across otherwise you may miss some of the changes...
